In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [2]:
df = pd.read_csv('/content/creditcard.csv')
df

        Time        V1        V2        V3  ...       V27       V28  Amount  Class
0          0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62    0.0
1          0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69    0.0
2          1 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66    0.0
3          1 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50    0.0
4          2 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99    0.0
...      ...       ...       ...       ...  ...       ...       ...     ...    ...
11954  20631  1.504204 -0.411728  0.200090  ... -0.012089  0.000905    9.00    0.0
11955  20636  1.134994  0.096340  0.277921  ...  0.012398 -0.009090    0.99    0.0
11956  20638 -6.305012  3.944886 -4.707362  ...  0.212900 -0.031021   89.99    0.0
11957  20638  1.161960 -0.398297  1.123732  ...  0.073836  0.028055   11.85    0.0
11958  20642  1.291096 -0.226628  0.708386  ...       NaN       NaN     NaN    NaN

[11959 rows x 31 columns]